### ISSUE TITLE
Any chance we could hook in autojump as a compliment?

### ISSUE THREAD

**Issue by NISH1001** [tnagorra/wd-nvim#1]
Basically, I like [autojump](https://github.com/wting/autojump/) which is -- as vaguely I am overstating here -- seems "wd" in auto mode.

**Comment by tnagorra** [comment]
I will have to first use autojump to understand how it works. Maybe someday!

**Comment by NISH1001** [comment]
Okay. I will try to see if I can do that too (assuming I am not bored...)
